// Auth Actions
export const CHANGE_FIRST_TIME = "CHANGE_FIRST_TIME";

export const SHOW_FEEDBACK = "SHOW_FEEDBACK";
export const CLEAR_FEEDBACK = "CLEAR_FEEDBACK";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const CLEAR_COUNTRIES = "CLEAR_COUNTRIES";
